name: get PRs from push

on:
  push:

jobs:
  get-prs:
    runs-on: ubuntu-latest

    steps:
      - name: payload
        run: cat $GITHUB_EVENT_PATH

      - name: get any PRs associated with commit pushed
        run: |
          curl -s -H "Accept: application/vnd.github.groot-preview+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls
